{{- /* Generate a service for each agent */}}
{{- range $name, $agent := .Values.agents }}
{{- if $agent.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kumeo.fullname" . }}-{{ $name | kebabcase }}
  labels:
    {{- include "kumeo.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: {{ $name | kebabcase }}
    app.kubernetes.io/name: {{ $name | kebabcase }}
spec:
  type: {{ $agent.service.type | default .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $agent.service.port | default .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if $agent.service.additionalPorts }}
    {{- range $port := $agent.service.additionalPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name | default (printf "port-%d" .port) | kebabcase }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "kumeo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: {{ $name | kebabcase }}
    app.kubernetes.io/name: {{ $name | kebabcase }}
{{- end }}
{{- end }}
