apiVersion: v2
name: kumeo-agent
description: A Helm chart for Kumeo Agents
type: application
version: 0.1.0
appVersion: "1.0.0"

# Dependencies for NATS and MinIO
dependencies:
  # NATS Server
  - name: nats
    version: "~0.19.0"
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled,global.nats.enabled
    tags:
      - kumeo-dependencies
      - nats

  # MinIO
  - name: minio
    version: "~5.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled,global.minio.enabled
    tags:
      - kumeo-dependencies
      - minio

# Default values for the chart
values:
  # Enable/disable NATS (enabled by default)
  nats:
    enabled: true
    # If external is true, the chart will not install NATS
    external: false
    # URL to an external NATS server if external is true
    url: ""
    
  # Enable/disable MinIO (enabled by default)
  minio:
    enabled: true
    # If external is true, the chart will not install MinIO
    external: false
    # Configuration for connecting to an external MinIO server
    endpoint: ""
    accessKey: ""
    secretKey: ""
    bucket: "kumeo"
    secure: false
