dependencies:
  # NATS Server
  - name: nats
    version: "~0.19.0"
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled,global.nats.enabled
    tags:
      - kumeo-dependencies
      - nats

  # MinIO
  - name: minio
    version: "~5.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled,global.minio.enabled
    tags:
      - kumeo-dependencies
      - minio
